### ISSUE TITLE
Too many newlines in cache files after crawling

### ISSUE THREAD

**Issue by RaBoom** [CfKu/check-bib-for-predatory#5]
Hi,
after crawling there are too many newlines in the .csv file so that reading the csv back in fails. 
This is on windows, for now I have just removed them with Notepad++ manually, which is inconvenient.

**Comment by CfKu** [comment]
Thanks for your respond. I guess both your issues #3 and #5 may be related to the OS. Could you propose a fix on Windows side for #5, as I only have macOS to test it?

**Comment by RaBoom** [comment]
According to [Stackoverflow](https://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row) the solution would be different for Python 2 or 3, for Python 3 (which I use), it would be adding `newline=''` to the `open()` call in line 94 (tried it, works).
The error exists, because the runtime on Windows converts \n to \r\n and the csv.writer uses \r\n on Windows, which makes it \r\r\n.
