### ISSUE TITLE
Add hijacked journals from beallslist.net

### ISSUE THREAD

**Issue by RaBoom** [CfKu/check-bib-for-predatory#8]
Spotting hijacked journals would be interesting too, but might need a different crawler because of the different page structure. I'm not familiar with how the crawling works, so I will not do it right now.
[Here](https://beallslist.net/hijacked-journals/) is the list of hijacked journals from beallslist.

**Comment by CfKu** [comment]
Hey @RaBoom, I'll have a look on your requests/issues during weekend, most probably.
