### ISSUE TITLE
Link to scam/lottery site in the README.md

### ISSUE THREAD

**Issue by fofusa** [CfKu/check-bib-for-predatory#9]
Hello,
It seems that the first 3 links in the readme point towards scam websites:

- https://predatoryjournals.com/journals/
- https://predatoryjournals.com/hijacked/
- https://predatoryjournals.com/publishers/

I hope it does not infer with the inner working of your app.

Fofusa

**Comment by CfKu** [comment]
Hi @fofusa,

thanks for the hint. I'll double-check the links. If I am not misstaken, I've cached the list. I am not sure, if there are newer once.

BR
CfKu
